//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dictionary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dictionary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a_1|https://www.oxfordlearnersdictionaries.com/media/english/uk_pron/a/a__/a__gb/a__gb_2.mp3
        ///a_2|https://www.oxfordlearnersdictionaries.com/media/english/uk_pron/a/a_1/a_1_g/a_1_gb_1_abbr.mp3
        ///a_3|https://www.oxfordlearnersdictionaries.com/media/english/uk_pron/a/a_1/a_1_g/a_1_gb_1_abbr.mp3
        ///a_4|https://www.oxfordlearnersdictionaries.com/media/english/uk_pron/a/a_1/a_1_g/a_1_gb_1_abbr.mp3
        ///a_5|https://www.oxfordlearnersdictionaries.com/media/english/uk_pron/a/a__/a__1_/a__1_gb_1.mp3
        ///aa_1|https://www.oxfordlear [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string british {
            get {
                return ResourceManager.GetString("british", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BrowseDefinition_16x {
            get {
                object obj = ResourceManager.GetObject("BrowseDefinition_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1A
        ///2C
        ///3D
        ///4C
        ///5A
        ///6D
        ///7B
        ///8A
        ///9C
        ///10A
        ///11B
        ///12C
        ///13B
        ///14C
        ///15D
        ///16C
        ///17D
        ///18D
        ///19C
        ///20D
        ///21D
        ///22A
        ///23D
        ///24A
        ///25D
        ///26A
        ///27C
        ///28D
        ///29C
        ///30C
        ///31A
        ///32A
        ///33D
        ///34C
        ///35A
        ///36B
        ///37A
        ///38C
        ///39C
        ///40D
        ///41D
        ///42D
        ///43D
        ///44C
        ///45A
        ///46B
        ///47A
        ///48D
        ///49B
        ///50D
        ///51A
        ///52C
        ///53A
        ///54B
        ///55D
        ///56A
        ///57D
        ///58D
        ///59A
        ///60A
        ///61C
        ///62B
        ///63B
        ///64C
        ///65A
        ///66C
        ///67A
        ///68C
        ///69B
        ///70D
        ///71A
        ///72C
        ///73A
        ///74C
        ///75B
        ///76A
        ///77A
        ///78D
        ///79C
        ///80A
        ///81C
        ///82D
        ///83A
        ///84B
        ///85C
        ///86B
        ///87D
        ///88C
        ///89D
        ///90A
        ///91B
        ///92D
        ///93A
        ///94B
        ///95A
        ///96B
        ///97C
        ///98A
        ///99D
        ///100C
        ///101D
        ///102C
        ///103C
        ///10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Collocation_Answers {
            get {
                return ResourceManager.GetString("Collocation_Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. He was late so I decided to _____ time by window shopping._A. kill_B. miss_C. spend_D. waste 
        ///2. John felt a sharp _____ in his back._A. injury_B. wound_C. pain_D. ache 
        ///3. The tomatoes we ate at their house were home-_____._A. made_B. produced_C. done_D. grown 
        ///4. Turn up to page 24 to find out at a _____ which courses are available to you._A. look_B. stare_C. glance_D. glimpse 
        ///5. The boys have gone on a fishing _____ with their father._A. trip_B. journey_C. trek_D. hike 
        ///6. I like that photo very [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Collocation_Quizzes {
            get {
                return ResourceManager.GetString("Collocation_Quizzes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @a /ei, ə/
        ///*  danh từ,  số nhiều as,  a&apos;s
        ///- (thông tục) loại a, hạng nhất, hạng tốt nhất hạng rất tốt
        ///=his health is a+ sức khoẻ anh ta vào loại a
        ///- (âm nhạc) la
        ///=a sharp+ la thăng
        ///=a flat+ la giáng
        ///- người giả định thứ nhất; trường hợp giả định thứ nhất
        ///=from a to z+ từ đầu đến đuôi, tường tận
        ///=not to know a from b+ không biết tí gì cả; một chữ bẻ đôi cũng không biết
        ///*  mạo từ
        ///- một; một (như kiểu); một (nào đó)
        ///=a very cold day+ một ngày rất lạnh
        ///=a dozen+ một tá
        ///=a few+ một ít
        ///=all of a si [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSDL {
            get {
                return ResourceManager.GetString("CSDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a|/ə/
        ///aa|/ˌeɪ ˈeɪ/
        ///aaa|/ˌtrɪpl ˈeɪ/
        ///aardvark|/ˈɑːdvɑːk/
        ///aargh|/ɑː(r)/
        ///aaron|/ˈeərən/
        ///aba|/ˌeɪ biː ˈeɪ/
        ///aback|/əˈbæk/
        ///abacus|/ˈæbəkəs/
        ///abaft|/əˈbɑːft/
        ///abalone|/ˌæbəˈləʊni/
        ///abandon|/əˈbændən/
        ///abandoned|/əˈbændənd/
        ///abandonment|/əˈbændənmənt/
        ///abase|/əˈbeɪs/
        ///abasement|/əˈbeɪsmənt/
        ///abashed|/əˈbæʃt/
        ///abate|/əˈbeɪt/
        ///abatement|/əˈbeɪtmənt/
        ///abattoir|/ˈæbətwɑː(r)/
        ///abba|/əˈbɑː/
        ///abbey|/ˈæbi/
        ///abbess|/ˈæbes/
        ///abbie|/ˈæbi/
        ///abbot|/ˈæbət/
        ///abbreviate|/əˈbriːvieɪt/
        ///abbreviated|/əˈbriːvieɪtɪd/
        ///abbreviat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EEWordAndSpelling {
            get {
                return ResourceManager.GetString("EEWordAndSpelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///aa
        ///aaa
        ///aardvark
        ///aargh
        ///aaron
        ///aba
        ///aback
        ///abacus
        ///abaft
        ///abalone
        ///abandon
        ///abandoned
        ///abandonment
        ///abase
        ///abasement
        ///abashed
        ///abate
        ///abatement
        ///abattoir
        ///abba
        ///abbey
        ///abbess
        ///abbie
        ///abbot
        ///abbreviate
        ///abbreviated
        ///abbreviation
        ///abc
        ///abd
        ///abdicate
        ///abdication
        ///abdomen
        ///abdominal
        ///abduct
        ///abduction
        ///abductor
        ///abe
        ///abed
        ///abeyance
        ///aberdeen
        ///aberdonian
        ///aberrant
        ///aberration
        ///abet
        ///abhor
        ///abhorrence
        ///abhorrent
        ///abide
        ///abiding
        ///abigail
        ///ability
        ///abiotic
        ///abysmal
        ///abysmally
        ///abyss
        ///abyssal
        ///abject
        ///abjectly        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EEWordList {
            get {
                return ResourceManager.GetString("EEWordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @a /ei, ə/
        ///*  danh từ,  số nhiều as,  a&apos;s
        ///- (thông tục) loại a, hạng nhất, hạng tốt nhất hạng rất tốt
        ///=his health is a+ sức khoẻ anh ta vào loại a
        ///- (âm nhạc) la
        ///=a sharp+ la thăng
        ///=a flat+ la giáng
        ///- người giả định thứ nhất; trường hợp giả định thứ nhất
        ///=from a to z+ từ đầu đến đuôi, tường tận
        ///=not to know a from b+ không biết tí gì cả; một chữ bẻ đôi cũng không biết
        ///*  mạo từ
        ///- một; một (như kiểu); một (nào đó)
        ///=a very cold day+ một ngày rất lạnh
        ///=a dozen+ một tá
        ///=a few+ một ít
        ///=all of a si [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EngViet {
            get {
                return ResourceManager.GetString("EngViet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///a b c
        ///a b c - book
        ///a font
        ///a fortiori
        ///a la carte
        ///a la mode
        ///a posteriori
        ///a priori
        ///a-bomb
        ///a-going
        ///a-plenty
        ///a-power
        ///a.d.
        ///a.m.
        ///aard-wolf
        ///aasvogel
        ///aba
        ///abaci
        ///aback
        ///abacus
        ///abaddon
        ///abaft
        ///abalone
        ///abandon
        ///abandoned
        ///abandoner
        ///abandonment
        ///abase
        ///abasement
        ///abash
        ///abashment
        ///abask
        ///abatable
        ///abate
        ///abatement
        ///abatis
        ///abatised
        ///abattoir
        ///abb
        ///abbacy
        ///abbatial
        ///abbess
        ///abbey
        ///abbot
        ///abbreviate
        ///abbreviated
        ///abbreviation
        ///abbreviator
        ///abdicant
        ///abdicate
        ///abdication
        ///abdicator
        ///abdomen
        ///abdomina [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVa {
            get {
                return ResourceManager.GetString("EVa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b
        ///b.a.
        ///b.b.c
        ///b.c
        ///baa
        ///baa-lamb
        ///babbit-metal
        ///babble
        ///babblement
        ///babbler
        ///babe
        ///babel
        ///babittry
        ///baboon
        ///babouche
        ///baby
        ///baby buggy
        ///baby-farm
        ///baby-farmer
        ///baby-farming
        ///baby-jumper
        ///baby-sit
        ///baby-sitter
        ///babyhood
        ///babyish
        ///babyishness
        ///babyism
        ///baccalaureate
        ///baccarat
        ///bacchanal
        ///bacchanalia
        ///bacchanalian
        ///bacchant
        ///bacchic
        ///bacchus
        ///bacciferous
        ///bacciform
        ///baccivorous
        ///baccy
        ///bachelor
        ///bachelorhood
        ///bachelorship
        ///bacillary
        ///bacilli
        ///bacilliform
        ///bacillus
        ///back
        ///back bench
        ///back door
        ///back number
        ///b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVb {
            get {
                return ResourceManager.GetString("EVb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c
        ///c.o.d.
        ///ca&apos;canny
        ///cab
        ///cab-rank
        ///cab-runner
        ///cab-stand
        ///cab-tout
        ///cabal
        ///cabala
        ///cabalism
        ///cabalistic
        ///caballer
        ///cabaret
        ///cabaret show
        ///cabbage
        ///cabbage-head
        ///cabbala
        ///cabbalism
        ///cabbalistic
        ///cabby
        ///caber
        ///cabin
        ///cabin-boy
        ///cabin-class
        ///cabinet
        ///cabinet-maker
        ///cabinet-making
        ///cabinet-work
        ///cable
        ///cable-car
        ///cablegram
        ///cablerailway
        ///cabman
        ///caboodle
        ///caboose
        ///cabotage
        ///cabriolet
        ///cacao
        ///cacao-tree
        ///cachalot
        ///cache
        ///cachet
        ///cachetic
        ///cachexy
        ///cachinnate
        ///cachinnation
        ///cachou
        ///cack
        ///cackle
        ///cacodylate
        ///caco [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVc {
            get {
                return ResourceManager.GetString("EVc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d
        ///d&apos;ye
        ///d-day
        ///d.ration
        ///da
        ///dab
        ///dabber
        ///dabble
        ///dabbler
        ///dabchick
        ///dabster
        ///dace
        ///dachshund
        ///dacoit
        ///dacoity
        ///dactyl
        ///dactylic
        ///dactylogram
        ///dactylography
        ///dactylogy
        ///dad
        ///daddy
        ///dado
        ///dady-long-legs
        ///daedal
        ///daedalian
        ///daemon
        ///daemonic
        ///daff
        ///daffadowndilly
        ///daffodil
        ///daffodilly
        ///daffy
        ///daft
        ///dagger
        ///daggle
        ///dago
        ///daguerreotype
        ///dahlia
        ///daily
        ///daintiness
        ///dainty
        ///dairy
        ///dairy cattle
        ///dairy-farm
        ///dairying
        ///dairymaid
        ///dairyman
        ///dais
        ///daisied
        ///daisy
        ///daisy-chain
        ///daisy-cutter
        ///dale
        ///dalesman
        ///dalliance
        ///da [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVd {
            get {
                return ResourceManager.GetString("EVd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e
        ///e&apos;en
        ///e&apos;er
        ///e-boat
        ///e.g
        ///each
        ///eager
        ///eagerness
        ///eagle
        ///eagle-eyed
        ///eaglet
        ///eagre
        ///ear
        ///ear-ache
        ///ear-drop
        ///ear-drops
        ///ear-drum
        ///ear-hole
        ///ear-phone
        ///ear-pick
        ///ear-ring
        ///ear-splitting
        ///ear-tab
        ///ear-trumpet
        ///ear-wax
        ///earing
        ///earl
        ///earldom
        ///earless
        ///earliness
        ///early
        ///early bird
        ///earmark
        ///earmuffs
        ///earn
        ///earnest
        ///earnestness
        ///earnings
        ///earser
        ///earshot
        ///earsure
        ///earth
        ///earth-bed
        ///earth-born
        ///earth-bound
        ///earth-flax
        ///earth-light
        ///earth-nut
        ///earth-shine
        ///earth-worm
        ///earthen
        ///earthenware
        ///earthiness
        ///earthlines [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVe {
            get {
                return ResourceManager.GetString("EVe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f
        ///f.o.
        ///fa
        ///fabian
        ///fable
        ///fabled
        ///fabler
        ///fabric
        ///fabricant
        ///fabricate
        ///fabricated
        ///fabrication
        ///fabricator
        ///fabulist
        ///fabulosity
        ///facade
        ///face
        ///face value
        ///face-ache
        ///face-card
        ///face-guard
        ///face-lift
        ///face-lifting
        ///facer
        ///facet
        ///faceted
        ///facetiae
        ///facetious
        ///facetiousness
        ///facia
        ///facial
        ///facile
        ///facilitate
        ///facility
        ///facing
        ///facsimile
        ///fact
        ///fact-finding
        ///faction
        ///factional
        ///factionalism
        ///factious
        ///factiousness
        ///factitious
        ///factitiousness
        ///factitive
        ///factor
        ///factorage
        ///factorial
        ///factory
        ///factotum
        ///factu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVf {
            get {
                return ResourceManager.GetString("EVf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g
        ///g.i.
        ///g.man
        ///gab
        ///gabardine
        ///gabber
        ///gabble
        ///gabbler
        ///gabbro
        ///gabby
        ///gaberdine
        ///gabion
        ///gabionade
        ///gable
        ///gabled
        ///gaby
        ///gad
        ///gad-fly
        ///gadabout
        ///gadder
        ///gadget
        ///gadoid
        ///gadwall
        ///gael
        ///gaelic
        ///gaff
        ///gaffe
        ///gaffer
        ///gag
        ///gag-man
        ///gaga
        ///gage
        ///gaggle
        ///gaiety
        ///gaily
        ///gain
        ///gainer
        ///gainful
        ///gainings
        ///gainly
        ///gainsaid
        ///gainsay
        ///gainst
        ///gait
        ///gaiter
        ///gal
        ///gala
        ///galactose
        ///galantine
        ///galanty show
        ///galatic
        ///galaxy
        ///gale
        ///galeate
        ///galeeny
        ///galen
        ///galena
        ///galenic
        ///galenical
        ///galimatias
        ///galingale
        ///galiot
        ///galipot
        ///gal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVg {
            get {
                return ResourceManager.GetString("EVg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h
        ///h-bomb
        ///h-hour
        ///ha
        ///ha ha
        ///ha&apos;p&apos;orth
        ///ha-ha
        ///haaf
        ///habanera
        ///habeas corpus
        ///haberdasher
        ///haberdashery
        ///habergeon
        ///habile
        ///habiliment
        ///habilitate
        ///habilitation
        ///habit
        ///habitability
        ///habitable
        ///habitableness
        ///habitant
        ///habitat
        ///habitation
        ///habitual
        ///habitude
        ///habitué
        ///hachure
        ///hacienda
        ///hack
        ///hack-hammer
        ///hack-saw
        ///hack-work
        ///hackberry
        ///hackbut
        ///hackery
        ///hacking
        ///hackle
        ///hackly
        ///hackmatack
        ///hackney
        ///hackney-carriage
        ///hackney-coach
        ///hackneyed
        ///hackstand
        ///had
        ///haddock
        ///hade
        ///hades
        ///hadn&apos;t
        ///haemal
        ///haematic
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVh {
            get {
                return ResourceManager.GetString("EVh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i
        ///i&apos;d
        ///i&apos;ll
        ///i&apos;m
        ///i&apos;ve
        ///i-beam
        ///i.e.
        ///i.q.
        ///iamb
        ///iambi
        ///iambic
        ///iambus
        ///iberian
        ///ibex
        ///ibices
        ///ibidem
        ///ibis
        ///ice
        ///ice cube
        ///ice water
        ///ice-age
        ///ice-axe
        ///ice-bag
        ///ice-boat
        ///ice-bound
        ///ice-box
        ///ice-breaker
        ///ice-cap
        ///ice-cold
        ///ice-cream
        ///ice-cream cone
        ///ice-drift
        ///ice-fall
        ///ice-field
        ///ice-fishing
        ///ice-floe
        ///ice-free
        ///ice-hockey
        ///ice-house
        ///ice-pack
        ///ice-pick
        ///ice-plant
        ///ice-pudding
        ///ice-rain
        ///ice-run
        ///ice-sheet
        ///ice-skate
        ///ice-wool
        ///ice-yacht
        ///iceberg
        ///iceblink
        ///iced
        ///icelander
        ///icelandic
        ///iceman
        ///ichneumon        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVi {
            get {
                return ResourceManager.GetString("EVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to j
        ///jaal-goat
        ///jab
        ///jabber
        ///jaborandi
        ///jabot
        ///jacinth
        ///jack
        ///jack frost
        ///jack ketch
        ///jack light
        ///jack pudding
        ///jack rabbit
        ///jack sprat
        ///jack tar
        ///jack-a-dandy
        ///jack-horse
        ///jack-in-the-box
        ///jack-knife
        ///jack-o&apos;-lantern
        ///jack-plane
        ///jack-priest
        ///jack-rafter
        ///jack-screw
        ///jack-snipe
        ///jack-staff
        ///jack-straw
        ///jack-towel
        ///jackal
        ///jackanapes
        ///jackaroo
        ///jackass
        ///jackboot
        ///jackdaw
        ///jacket
        ///jackhammer
        ///jackpot
        ///jacob&apos;s ladder
        ///jacob&apos;s staff
        ///jacobean
        ///jacobin
        ///jacobinic
        ///jacobinical
        ///jacobinism
        ///jaconet
        ///jacquard loom
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVj {
            get {
                return ResourceManager.GetString("EVj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to k
        ///k-ration
        ///kaama
        ///kabbalah
        ///kadi
        ///kaff
        ///kaftan
        ///kago
        ///kaiak
        ///kail
        ///kailyard
        ///kaingin
        ///kainite
        ///kaiser
        ///kaka
        ///kakemono
        ///kala-azar
        ///kale
        ///kaleidoscope
        ///kaleidoscopic
        ///kaleidoscopical
        ///kalends
        ///kaleyard
        ///kali
        ///kalium
        ///kalong
        ///kampometer
        ///kampong
        ///kanaka
        ///kangaroo
        ///kantian
        ///kantianism
        ///kaoliang
        ///kaolin
        ///kaolinise
        ///kaolinization
        ///kaolinize
        ///kapellmeister
        ///kapok
        ///kaput
        ///karakul
        ///karma
        ///karoo
        ///kaross
        ///kartel
        ///kartell
        ///karyokinesis
        ///karyoplasm
        ///katabatic
        ///katabolism
        ///katamorphic
        ///katamorphism
        ///kathode
        ///kation
        ///ka [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVk {
            get {
                return ResourceManager.GetString("EVk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l
        ///l-bar
        ///l.s.d
        ///la
        ///la-breaker
        ///la-di-da
        ///laager
        ///lab
        ///labefaction
        ///label
        ///labeller
        ///labia
        ///labial
        ///labialization
        ///labialize
        ///labiate
        ///labile
        ///lability
        ///labiodental
        ///labium
        ///labor
        ///labor day
        ///laboratorial
        ///laboratorian
        ///laboratory
        ///laboratory school
        ///laborious
        ///labour
        ///labour exchange
        ///labour force
        ///labour leader
        ///labour movement
        ///labour of love
        ///labour party
        ///labour relations
        ///labour-market
        ///labour-saving
        ///laboured
        ///labourer
        ///labouring
        ///labourist
        ///labourite
        ///labra
        ///labrum
        ///laburnum
        ///labyrinth
        ///labyrinthia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVl {
            get {
                return ResourceManager.GetString("EVl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m
        ///m-day
        ///m.a
        ///m.d.
        ///m.p.
        ///ma
        ///ma&apos;am
        ///macabre
        ///macaco
        ///macadam
        ///macadamise
        ///macadamization
        ///macadamize
        ///macaroni
        ///macaroon
        ///macaw
        ///maccabaw
        ///maccaboy
        ///mace
        ///macerate
        ///maceration
        ///macerative
        ///macerator
        ///mach number
        ///machete
        ///machiavel
        ///machiavelli
        ///machiavellian
        ///machiavellianism
        ///machiavellism
        ///machicolate
        ///machicolation
        ///machicoulis
        ///machinability
        ///machinable
        ///machinate
        ///machination
        ///machinator
        ///machine
        ///machine-gun
        ///machine-gunner
        ///machine-made
        ///machine-shop
        ///machine-tool
        ///machinery
        ///machinist
        ///mackerel
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVm {
            get {
                return ResourceManager.GetString("EVm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n
        ///n&apos;t
        ///nab
        ///nabob
        ///nacarat
        ///nacelle
        ///nacreous
        ///nacrous
        ///nadir
        ///nadiral
        ///naevi
        ///naevus
        ///nag
        ///nagger
        ///nagging
        ///naggish
        ///naggy
        ///naiad
        ///naif
        ///nail
        ///nail drawer
        ///nail-biting
        ///nail-brush
        ///nail-file
        ///nail-head
        ///nail-polish
        ///nail-scissors
        ///nailer
        ///nailery
        ///nainsook
        ///naive
        ///naivety
        ///naja
        ///naked
        ///nakedness
        ///namby-pambiness
        ///namby-pamby
        ///namby-pambyism
        ///name
        ///name-caller
        ///name-calling
        ///name-child
        ///name-day
        ///name-part
        ///name-plate
        ///nameless
        ///namely
        ///namesake
        ///nance
        ///nancy
        ///nandu
        ///nanism
        ///nankeen
        ///nanny
        ///nanny-goat
        ///nap [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVn {
            get {
                return ResourceManager.GetString("EVn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o
        ///o yes
        ///o&apos;
        ///o&apos;clock
        ///o&apos;er
        ///o.k.
        ///o.pip
        ///oaf
        ///oafish
        ///oak
        ///oak-apple
        ///oak-fig
        ///oak-gall
        ///oak-nut
        ///oak-wood
        ///oaken
        ///oaklet
        ///oakling
        ///oakum
        ///oar
        ///oar-lock
        ///oarage
        ///oared
        ///oarer
        ///oarless
        ///oarsman
        ///oarsmanship
        ///oary
        ///oases
        ///oasis
        ///oast
        ///oast-house
        ///oat
        ///oatcake
        ///oaten
        ///oath
        ///oath-breaker
        ///oath-breaking
        ///oatmeal
        ///oaves
        ///ob.
        ///obbligato
        ///obconical
        ///obcordate
        ///obduracy
        ///obdurate
        ///obeah
        ///obedience
        ///obedient
        ///obedientiary
        ///obeisance
        ///obeisant
        ///obeli
        ///obelisk
        ///obelize
        ///obelus
        ///obese
        ///obesity
        ///obey
        ///obfuscate
        ///obfusca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVo {
            get {
                return ResourceManager.GetString("EVo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p
        ///p.m.
        ///pa
        ///pabulum
        ///pace
        ///pace-maker
        ///pacer
        ///pacha
        ///pachyderm
        ///pachydermatous
        ///pacific
        ///pacification
        ///pacificator
        ///pacificatory
        ///pacificism
        ///pacificist
        ///pacifier
        ///pacifism
        ///pacifist
        ///pacify
        ///pack
        ///pack-animal
        ///pack-drill
        ///pack-horse
        ///pack-ice
        ///pack-saddle
        ///package
        ///package deal
        ///packer
        ///packet
        ///packet-boat
        ///packing
        ///packing-case
        ///packing-needle
        ///packing-paper
        ///packing-sheet
        ///packman
        ///packpaper
        ///packthread
        ///pact
        ///pad
        ///padding
        ///paddle
        ///paddle board
        ///paddle-box
        ///paddle-wheel
        ///paddlefish
        ///paddock
        ///paddy
        ///padd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVp {
            get {
                return ResourceManager.GetString("EVp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q
        ///q-boat
        ///q-ship
        ///qu.
        ///qua
        ///quacdragesima
        ///quacdragesimal
        ///quack
        ///quack-quack
        ///quackery
        ///quackish
        ///quacksalver
        ///quad
        ///quadragenarian
        ///quadrangle
        ///quadrangular
        ///quadrant
        ///quadrat
        ///quadrate
        ///quadratic
        ///quadrature
        ///quadrennial
        ///quadric
        ///quadriga
        ///quadrigae
        ///quadrilateral
        ///quadrilingual
        ///quadrille
        ///quadrillion
        ///quadripartite
        ///quadripole
        ///quadrisyllabic
        ///quadrisyllable
        ///quadrivalence
        ///quadrivalency
        ///quadrivalent
        ///quadroon
        ///quadrumanous
        ///quadruped
        ///quadrupedal
        ///quadruple
        ///quadruplet
        ///quadruplicate
        ///quadruplicati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVq {
            get {
                return ResourceManager.GetString("EVq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r
        ///rabbet
        ///rabbi
        ///rabbin
        ///rabbit
        ///rabbit-fever
        ///rabbit-hole
        ///rabbit-hutch
        ///rabbit-punch
        ///rabbit-warren
        ///rabbitry
        ///rabbity
        ///rabble
        ///rabble rouser
        ///rabid
        ///rabidity
        ///rabidness
        ///rabies
        ///raccoon
        ///race
        ///race riot
        ///race-card
        ///race-meeting
        ///race-way
        ///racecourse
        ///racehorse
        ///raceme
        ///racemose
        ///racer
        ///racetrack
        ///rachitis
        ///racial
        ///racialism
        ///racialist
        ///raciness
        ///racism
        ///racist
        ///rack
        ///rack-rail
        ///rack-railway
        ///rack-rent
        ///rack-renter
        ///rack-wheel
        ///racket
        ///racketeer
        ///raconteur
        ///racoon
        ///racquet
        ///racy
        ///radar
        ///raddle
        ///raddled
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVr {
            get {
                return ResourceManager.GetString("EVr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s
        ///s o s
        ///s-o-b
        ///sabaean
        ///sabaism
        ///sabbatarian
        ///sabbath
        ///sabbatic
        ///sabbatise
        ///sabbatize
        ///sabean
        ///saber
        ///sabicu
        ///sable
        ///sabot
        ///sabotage
        ///saboteur
        ///sabre
        ///sabretache
        ///sabreur
        ///sabulous
        ///sac
        ///saccate
        ///saccharate
        ///saccharic
        ///saccharide
        ///sacchariferous
        ///saccharification
        ///saccharify
        ///saccharimeter
        ///saccharimetry
        ///saccharin
        ///saccharine
        ///saccharoid
        ///saccharometer
        ///saccharose
        ///sacciform
        ///saccule
        ///sacerdocy
        ///sacerdotage
        ///sacerdotal
        ///sacerdotalism
        ///sachem
        ///sachet
        ///sack
        ///sack-coat
        ///sack-race
        ///sackbut
        ///sackcloth
        ///sacker [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVs {
            get {
                return ResourceManager.GetString("EVs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t
        ///t&apos;other
        ///t-shirt
        ///ta
        ///ta-ta
        ///tab
        ///tabard
        ///tabaret
        ///tabby
        ///tabefaction
        ///tabernacle
        ///tabes
        ///tabescence
        ///tabetic
        ///table
        ///table d&apos;hôte
        ///table-cloth
        ///table-companion
        ///table-cover
        ///table-diamond
        ///table-flap
        ///table-fork
        ///table-knife
        ///table-leaf
        ///table-linen
        ///table-spoon
        ///table-spoonful
        ///table-tomb
        ///table-ware
        ///table-water
        ///tableau
        ///tableaux
        ///tableful
        ///tableland
        ///tablet
        ///tablet tennis
        ///tablet-talk
        ///tabloid
        ///taboo
        ///tabor
        ///taboret
        ///tabouret
        ///tabu
        ///tabular
        ///tabulate
        ///tabulating machine
        ///tabulation
        ///tabulator
        ///tacfu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVt {
            get {
                return ResourceManager.GetString("EVt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to u
        ///u-boat
        ///u-turn
        ///u.p.
        ///ubiety
        ///ubiquitous
        ///ubiquitousness
        ///ubiquity
        ///udder
        ///uddered
        ///udometer
        ///ugh
        ///uglification
        ///uglify
        ///ugliness
        ///ugly
        ///uhlan
        ///ukase
        ///ukrainian
        ///ukulele
        ///ulcer
        ///ulcerate
        ///ulcerated
        ///ulceration
        ///ulcerative
        ///ulcered
        ///ulcerous
        ///ulex
        ///uliginal
        ///uliginose
        ///uliginous
        ///ullage
        ///ullaged
        ///ulna
        ///ulnae
        ///ulnar
        ///ulster
        ///ult.
        ///ulterior
        ///ultima
        ///ultimate
        ///ultimately
        ///ultimatum
        ///ultimo
        ///ultimogeniture
        ///ultra
        ///ultra vires
        ///ultra-rapid
        ///ultra-short
        ///ultra-sound
        ///ultra-violet
        ///ultraconservative
        ///ultraism
        ///u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVu {
            get {
                return ResourceManager.GetString("EVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        ///v-day
        ///v-e day
        ///v-j day
        ///vac
        ///vacancy
        ///vacant
        ///vacate
        ///vacation
        ///vacationist
        ///vaccilation
        ///vaccinal
        ///vaccinate
        ///vaccination
        ///vaccinator
        ///vaccine
        ///vaccinia
        ///vacillate
        ///vacillating
        ///vacillatory
        ///vacoular
        ///vacoulate
        ///vacoulated
        ///vacoule
        ///vacua
        ///vacuity
        ///vacuous
        ///vacuum
        ///vacuum bottle
        ///vacuum brake
        ///vacuum cleaner
        ///vacuum desiccator
        ///vacuum drier
        ///vacuum fan
        ///vacuum filter
        ///vacuum flask
        ///vacuum-clean
        ///vacuum-gauge
        ///vacuum-pump
        ///vacuum-tube
        ///vacuum-valve 
        ///vagabond
        ///vagabondage
        ///vagabondism
        ///vagabondize
        ///vaga [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVv {
            get {
                return ResourceManager.GetString("EVv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w
        ///w.c.
        ///wabble
        ///wabbly
        ///wacky
        ///wad
        ///wadding
        ///waddle
        ///waddling
        ///waddy
        ///wade
        ///wader
        ///wadi
        ///wading bird
        ///wafer
        ///waffle
        ///waffle-iron
        ///waft
        ///wag
        ///wage
        ///wage hike
        ///wage-earner
        ///wage-freeze
        ///wage-fund
        ///wage-rise
        ///wage-scale
        ///wage-sheet
        ///wager
        ///wagerer
        ///wages-fund
        ///waggery
        ///waggish
        ///waggishness
        ///waggle
        ///waggly
        ///waggon
        ///waggoner
        ///waggonette
        ///wagon
        ///wagon-lit
        ///wagoner
        ///wagonette
        ///wagtail
        ///waif
        ///wail
        ///wailful
        ///wainscot
        ///wainscoting
        ///waist
        ///waist-band
        ///waist-deep
        ///waist-line
        ///waistcoat
        ///wait
        ///wait-and-see
        ///waiter
        ///wai [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVw {
            get {
                return ResourceManager.GetString("EVw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @a /ei, ə/
        ///@a b c /&apos;eibi:&apos;si:/
        ///@a b c - book /&apos;eibi:&apos;si:buk/
        ///@a font /ɑ:&apos;fɜ:ɳ/
        ///@a fortiori /&apos;ei,fɔ:ti&apos;ɔ:rai/
        ///@a la carte /&apos;ɑ:lɑ:&apos;kɑ:t/
        ///@a la mode /,ɑ:lə&apos;moud/
        ///@a posteriori /&apos;eipɔs,teri&apos;ɔ:rai/
        ///@a priori /&apos;eiprai&apos;ɔ:rai/
        ///@a-bomb /&apos;ei&apos;bɔm/
        ///@a-going /ə&apos;gouiɳ/
        ///@a-plenty /ə&apos;plenti/
        ///@a-power /&apos;ei&apos;pauə/
        ///@a.d. /&apos;ei&apos;di:/
        ///@a.m. /&apos;ei&apos;em/
        ///@aard-wolf /&apos;ɑ:d,wulf/
        ///@aasvogel /&apos;ɑ:sfougəl/
        ///@aba /&apos;ɑ:bə/
        ///@abaci /&apos;æbəkəs/
        ///@aback /ə&apos;bæk/
        ///@abacus /&apos;æbəkəs/
        ///@abaddon /ə&apos;bædən/
        ///@abaft /ə&apos;bɑ:ft/
        ///@abalone /,æbə&apos;l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVWordAndSpelling {
            get {
                return ResourceManager.GetString("EVWordAndSpelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///a b c
        ///a b c - book
        ///a font
        ///a fortiori
        ///a la carte
        ///a la mode
        ///a posteriori
        ///a priori
        ///a-bomb
        ///a-going
        ///a-plenty
        ///a-power
        ///a.d.
        ///a.m.
        ///aard-wolf
        ///aasvogel
        ///aba
        ///abaci
        ///aback
        ///abacus
        ///abaddon
        ///abaft
        ///abalone
        ///abandon
        ///abandoned
        ///abandoner
        ///abandonment
        ///abase
        ///abasement
        ///abash
        ///abashment
        ///abask
        ///abatable
        ///abate
        ///abatement
        ///abatis
        ///abatised
        ///abattoir
        ///abb
        ///abbacy
        ///abbatial
        ///abbess
        ///abbey
        ///abbot
        ///abbreviate
        ///abbreviated
        ///abbreviation
        ///abbreviator
        ///abdicant
        ///abdicate
        ///abdication
        ///abdicator
        ///abdomen
        ///abdomina [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVWordList {
            get {
                return ResourceManager.GetString("EVWordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///a b c
        ///a b c - book
        ///a font
        ///a fortiori
        ///a la carte
        ///a la mode
        ///a posteriori
        ///a priori
        ///a-bomb
        ///a-going
        ///a-plenty
        ///a-power
        ///a.d.
        ///a.m.
        ///aard-wolf
        ///aasvogel
        ///aba
        ///abaci
        ///aback
        ///abacus
        ///abaddon
        ///abaft
        ///abalone
        ///abandon
        ///abandoned
        ///abandoner
        ///abandonment
        ///abase
        ///abasement
        ///abash
        ///abashment
        ///abask
        ///abatable
        ///abate
        ///abatement
        ///abatis
        ///abatised
        ///abattoir
        ///abb
        ///abbacy
        ///abbatial
        ///abbess
        ///abbey
        ///abbot
        ///abbreviate
        ///abbreviated
        ///abbreviation
        ///abbreviator
        ///abdicant
        ///abdicate
        ///abdication
        ///abdicator
        ///abdomen
        ///abdomina [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVWordName {
            get {
                return ResourceManager.GetString("EVWordName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x
        ///x-axis
        ///x-ray
        ///xanthate
        ///xanthic
        ///xanthine
        ///xanthippe
        ///xanthophyll
        ///xanthous
        ///xebec
        ///xenogamy
        ///xenomorphic
        ///xenon
        ///xenophobe
        ///xenophobia
        ///xerophilous
        ///xerophthalmia
        ///xerophyte
        ///xiphoid
        ///xmas
        ///xylem
        ///xylocarp
        ///xylocarpous
        ///xylograph
        ///xylographer
        ///xylography
        ///xylonite
        ///xylophagous
        ///xylophone
        ///xyster
        ///x-rated
        ///xbase
        ///xcmd
        ///xcnf
        ///xenix
        ///xenophilia
        ///xenophilous
        ///xenophobic
        ///xerophagy
        ///xerox
        ///xga
        ///xhosa
        ///xia
        ///xin
        ///xl
        ///xmodem
        ///xms
        ///xo
        ///xx
        ///xylen
        ///xyloid
        ///xi
        ///x-rays
        ///.
        /// </summary>
        internal static string EVx {
            get {
                return ResourceManager.GetString("EVx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y
        ///y-axis
        ///y-shaped
        ///yacht
        ///yacht-club
        ///yachting
        ///yachtsman
        ///yachtsmanship
        ///yaffil
        ///yaffle
        ///yah
        ///yahoo
        ///yak
        ///yale lock
        ///yam
        ///yammer
        ///yank
        ///yankee
        ///yankeefied
        ///yankeeism
        ///yaourt
        ///yap
        ///yard
        ///yard-master
        ///yard-wand
        ///yardage
        ///yardman
        ///yardstick
        ///yarn
        ///yarn-beam
        ///yarovization
        ///yarovize
        ///yarrow
        ///yashmak
        ///yaw
        ///yawing
        ///yawl
        ///yawn
        ///yawner
        ///yawningly
        ///yawny
        ///yaws
        ///yclept
        ///ye
        ///yea
        ///yean
        ///yeanling
        ///year
        ///year&apos;s mind
        ///yearling
        ///yearlong
        ///yearly
        ///yearn
        ///yearning
        ///yeast
        ///yeastiness
        ///yeasty
        ///yegg
        ///yeggman
        ///yeld
        ///yelk
        ///yell [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVy {
            get {
                return ResourceManager.GetString("EVy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z
        ///z-day
        ///zaffer
        ///zambo
        ///zany
        ///zeal
        ///zealot
        ///zealotism
        ///zealotry
        ///zealous
        ///zealousness
        ///zebra
        ///zebra markings
        ///zebu
        ///zed
        ///zee
        ///zemindar
        ///zenana
        ///zenith
        ///zenithal
        ///zeolite
        ///zephyr
        ///zepp
        ///zeppelin
        ///zero
        ///zest
        ///zeus
        ///zibet
        ///zigzag
        ///zigzagging
        ///zigzaggy
        ///zinc
        ///zinc-block
        ///zinciferous
        ///zinco
        ///zincograph
        ///zincographer
        ///zincographic
        ///zincography
        ///zingiberaceous
        ///zinnia
        ///zionism
        ///zionist
        ///zip
        ///zip-fastener
        ///zipper
        ///zircon
        ///zirconium
        ///zither
        ///zithern
        ///zloty
        ///zodiac
        ///zodiacal
        ///zoic
        ///zollverein
        ///zonal
        ///zonate
        ///zone
        ///z [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EVz {
            get {
                return ResourceManager.GetString("EVz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a_1|NA|37874951|NA|a man/horse/unit
        ///a_1|NA|37874951|NA|an aunt/egg/hour/X-ray
        ///a_1|NA|37874951|NA|I can only carry two at a time.
        ///a_1|NA|37874951|NA|There&apos;s a visitor for you.
        ///a_1|NA|37874951|NA|She&apos;s a friend of my father&apos;s (= one of my father&apos;s friends).
        ///a_1|NA|83922891|NA|Their new car&apos;s a BMW.
        ///a_1|NA|83922891|NA|She&apos;s a Buddhist.
        ///a_1|NA|83922891|NA|He&apos;s a teacher.
        ///a_1|NA|83922891|NA|Is that a Monet (= a painting by Monet)?
        ///a_1|NA|40666782|NA|A lion is a dangerous animal.
        ///a_1|NA|6086514|NA|a goo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string examples {
            get {
                return ResourceManager.GetString("examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a_2|A-frame
        ///a_2|A level
        ///a_2|A-road
        ///aback_1|take somebody aback
        ///abiding_1|law-abiding
        ///ability_1|mixed-ability
        ///ably_1|able (2)
        ///abode_1|right of abode
        ///above_2|(above and) beyond the call of duty
        ///abraham_2|Gettysburg Address
        ///abraham_2|Lincoln Memorial
        ///abs_2|anti-lock
        ///absolute_1|decree absolute
        ///absorb_1|shock absorber
        ///abuse_1|racket abuse
        ///abuse_1|racquet abuse
        ///abuse_1|solvent abuse
        ///abuse_1|substance abuse
        ///abuse_1|child abuse
        ///abuse_1|elder abuse
        ///abuse_1|self-abuse
        ///accent_1|acute accent
        ///acces [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string extra_list {
            get {
                return ResourceManager.GetString("extra_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap games {
            get {
                object obj = ResourceManager.GetObject("games", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap games2 {
            get {
                object obj = ResourceManager.GetObject("games2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap games3 {
            get {
                object obj = ResourceManager.GetObject("games3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap games4 {
            get {
                object obj = ResourceManager.GetObject("games4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap history {
            get {
                object obj = ResourceManager.GetObject("history", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Home_16x {
            get {
                object obj = ResourceManager.GetObject("Home_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1B
        ///2D
        ///3B
        ///4B
        ///5A
        ///6D
        ///7B
        ///8C
        ///9B
        ///10C
        ///11C
        ///12B
        ///13D
        ///14B
        ///15B
        ///16C
        ///17C
        ///18A
        ///19C
        ///20B
        ///21D
        ///22D
        ///23C
        ///24D
        ///25B
        ///26A
        ///27B
        ///28C
        ///29D
        ///30B
        ///31D
        ///32C
        ///33B
        ///34B
        ///35A
        ///36D
        ///37A
        ///38A
        ///39D
        ///40C
        ///41B
        ///42C
        ///43B
        ///44A
        ///45A
        ///46C
        ///47D
        ///48C
        ///49D
        ///50B
        ///51C
        ///52B
        ///53A
        ///54D
        ///55C
        ///56C
        ///57B
        ///58C
        ///59A
        ///60D
        ///61C
        ///62D
        ///63D
        ///64D
        ///65B
        ///66B
        ///67B
        ///68C
        ///69C
        ///70B
        ///71B
        ///72C
        ///73B
        ///74D
        ///75A
        ///76B
        ///77B
        ///78B
        ///79C
        ///80C
        ///81D
        ///82D
        ///83B
        ///84A
        ///85A
        ///86A
        ///87A
        ///88D
        ///89B
        ///90D
        ///91A
        ///92A
        ///93D
        ///94B
        ///95C
        ///96B
        ///97A
        ///98D
        ///99C
        ///100A
        ///101A
        ///102C
        ///103C
        ///10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Idiom_Answers {
            get {
                return ResourceManager.GetString("Idiom_Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. It finally _____ home to me that it was time to buy a place of my own._A. arrived_B. came_C. hit_D. reached 
        ///2. Well, it’s 7 p.m. I’d better hit the _____ if I want to get home before it’s dark_A. roof_B. headlines_C. newspaper_D. road 
        ///3. She’s the type who can’t sit on holiday and is always _____ the move._A. in_B. on_C. at_D. by 
        ///4. She had never been to Prague before, and she _____ in love with it straight away._A. dropped_B. fell_C. tripped_D. crashed 
        ///5. He didn’t speak a word of French when he [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Idiom_Quizzes {
            get {
                return ResourceManager.GetString("Idiom_Quizzes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info2 {
            get {
                object obj = ResourceManager.GetObject("info2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InformationSymbol_16x {
            get {
                object obj = ResourceManager.GetObject("InformationSymbol_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marked {
            get {
                object obj = ResourceManager.GetObject("marked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marked2 {
            get {
                object obj = ResourceManager.GetObject("marked2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menu {
            get {
                object obj = ResourceManager.GetObject("menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menu2 {
            get {
                object obj = ResourceManager.GetObject("menu2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menu3 {
            get {
                object obj = ResourceManager.GetObject("menu3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1D
        ///2C
        ///3B
        ///4A
        ///5A
        ///6C
        ///7D
        ///8D
        ///9B
        ///10B
        ///11B
        ///12C
        ///13C
        ///14C
        ///15B
        ///16B
        ///17A
        ///18B
        ///19B
        ///20A
        ///21A
        ///22B
        ///23D
        ///24C
        ///25B
        ///26A
        ///27A
        ///28A
        ///29D
        ///30C
        ///31B
        ///32A
        ///33D
        ///34B
        ///35A
        ///36D
        ///37A
        ///38A
        ///39B
        ///40D
        ///41C
        ///42D
        ///43B
        ///44C
        ///45C
        ///46D
        ///47B
        ///48C
        ///49D
        ///50C
        ///51D
        ///52A
        ///53B
        ///54C
        ///55D
        ///56C
        ///57B
        ///58B
        ///59D
        ///60C
        ///61D
        ///62C
        ///63C
        ///64D
        ///65C
        ///66A
        ///67B
        ///68B
        ///69A
        ///70C
        ///71D
        ///72D
        ///73A
        ///74D
        ///75C
        ///76A
        ///77B
        ///78C
        ///79B
        ///80B
        ///81B
        ///82C
        ///83B
        ///84B
        ///85A
        ///86B
        ///87C
        ///88B
        ///89B
        ///90C
        ///91C
        ///92A
        ///93D
        ///94D
        ///95C
        ///96A
        ///97C
        ///98C
        ///99B
        ///100A
        ///101A
        ///102A
        ///103D
        ///10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Phrasal_Verbs_Answers {
            get {
                return ResourceManager.GetString("Phrasal_Verbs_Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. We are _____ down too many trees all over the world._A. breaking_B. knocking_C. pushing_D. cutting 
        ///2. She has not yet got _____ her recent illness._A. by_B. through_C. over_D. out of 
        ///3. Everyone is going to take _____ in the game._A. place_B. part_C. participation_D. role 
        ///4. John was tidying the living room while I was cleaning _____ the dirt from thr dishes._A. away_B. out_C. up_D. off 
        ///5. “It takes about 2 hours, so we should _____ at about six o’clock.”_A. get in_B. get in it_C. get it in_D. ge [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Phrasal_Verbs_Quizzes {
            get {
                return ResourceManager.GetString("Phrasal_Verbs_Quizzes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap randomize {
            get {
                object obj = ResourceManager.GetObject("randomize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abiding_1|NA|73977648|law-abiding
        ///ability_1|NA|92718933|mixed-ability
        ///ably_1|NA|9580683|able (2)
        ///abode_1|NA|59875945|right of abode
        ///abraham_2|NA|46342902|Gettysburg Address
        ///abraham_2|NA|46342902|Lincoln Memorial
        ///abs_2|NA|8540525|anti-lock
        ///absolute_1|NA|67095304|decree absolute
        ///absorb_1|NA|13607302|shock absorber
        ///abuse_1|NA|79957152|racket abuse
        ///abuse_1|NA|79957152|racquet abuse
        ///abuse_1|NA|79957152|solvent abuse
        ///abuse_1|NA|79957152|substance abuse
        ///abuse_1|NA|88642875|child abuse
        ///abuse_1|NA|8864 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string see_also {
            get {
                return ResourceManager.GetString("see_also", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a_1|NA|used before countable or singular nouns referring to people or things that have not already been mentioned|a1|NA|NA|37874951
        ///a_1|NA|used to show that somebody/something is a member of a group or profession|a1|NA|NA|83922891
        ///a_1|NA|any; every|a1|NA|NA|40666782
        ///a_1|NA|used before uncountable nouns when these have an adjective in front of them, or phrase following them|b1|NA|NA|6086514
        ///a_1|NA|used in front of two nouns that are seen as a single unit|NA|NA|NA|10333066
        ///a_1|NA|used instead of one befo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string senses {
            get {
                return ResourceManager.GetString("senses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to absorb_1|liquid/gas
        ///absorb_1|heat/light/energy/sound
        ///absorb_1|shock/impact
        ///absorb_1|information
        ///absorb_1|interest somebody
        ///absorb_1|make part of something larger
        ///absorb_1|money/time/changes
        ///accept_1|offer/invitation
        ///accept_1|agree
        ///accept_1|payment
        ///accept_1|responsibility
        ///accept_1|difficult situation
        ///accept_1|welcome
        ///accept_1|believe
        ///accept_1|allow somebody to join
        ///account_1|at bank
        ///account_1|computing
        ///account_1|description
        ///account_1|business records
        ///account_1|with shop
        ///account_1|bill
        ///ac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string shortcuts {
            get {
                return ResourceManager.GetString("shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a_1|uk_pron_a_a__a__gb_a__gb_2.mp3
        ///a_2|uk_pron_a_a_1_a_1_g_a_1_gb_1_abbr.mp3
        ///a_3|uk_pron_a_a_1_a_1_g_a_1_gb_1_abbr.mp3
        ///a_4|uk_pron_a_a_1_a_1_g_a_1_gb_1_abbr.mp3
        ///a_5|uk_pron_a_a__a__1__a__1_gb_1.mp3
        ///aa_1|uk_pron_a_a_a_a_a__a_a__1_gb_1_abbr.mp3
        ///aaa_1|uk_pron_t_tri_tripl_triple_a_1_gb_1.mp3
        ///aardvark_1|uk_pron_a_aar_aardv_aardvark__gb_1.mp3
        ///aargh_1|uk_pron_a_aar_aargh_aargh__gb_1.mp3
        ///aaron_1|uk_pron_a_aar_aaron_aaron__gb_2.mp3
        ///aba_1|uk_pron_a_aba_aba__aba__gb_1.mp3
        ///aback_1|uk_pron_a_aba_aback_aback__ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string soundpath {
            get {
                return ResourceManager.GetString("soundpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap speaker {
            get {
                object obj = ResourceManager.GetObject("speaker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unmarked {
            get {
                object obj = ResourceManager.GetObject("unmarked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abandon_1|present simple I / you / we / they|  abandon|/əˈbændən/|uk_pron/a/aba/aband/abandon__gb_2.mp3|/əˈbændən/|us_pron/a/aba/aband/abandon__us_2.mp3
        ///abandon_1|he / she / it|  abandons|/əˈbændənz/|uk_pron/a/aba/aband/abandons__gb_1.mp3|/əˈbændənz/|us_pron/a/aba/aband/abandons__us_1.mp3
        ///abandon_1|past simple|  abandoned|/əˈbændənd/|uk_pron/a/aba/aband/abandoned__gb_1.mp3|/əˈbændənd/|us_pron/a/aba/aband/abandoned__us_1.mp3
        ///abandon_1|past participle|  abandoned|/əˈbændənd/|uk_pron/a/aba/aband/abandoned__ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string word_forms {
            get {
                return ResourceManager.GetString("word_forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1A
        ///2C
        ///3C
        ///4B
        ///5A
        ///6C
        ///7D
        ///8C
        ///9C
        ///10A
        ///11A
        ///12D
        ///13B
        ///14B
        ///15B
        ///16A
        ///17D
        ///18C
        ///19B
        ///20D
        ///21C
        ///22D
        ///23A
        ///24A
        ///25A
        ///26A
        ///27B
        ///28B
        ///29D
        ///30B
        ///31B
        ///32D
        ///33D
        ///34B
        ///35A
        ///36B
        ///37B
        ///38D
        ///39C
        ///40C
        ///41C
        ///42B
        ///43A
        ///44B
        ///45B
        ///46A
        ///47D
        ///48B
        ///49B
        ///50A
        ///51A
        ///52A
        ///53A
        ///54C
        ///55C
        ///56B
        ///57B
        ///58A
        ///59B
        ///60B
        ///61C
        ///62A
        ///63A
        ///64C
        ///65D
        ///66B
        ///67A
        ///68D
        ///69B
        ///70D
        ///71A
        ///72B
        ///73A
        ///74B
        ///75D
        ///76B
        ///77C
        ///78C
        ///79B
        ///80B
        ///81D
        ///82D
        ///83A
        ///84B
        ///85C
        ///86A
        ///87B
        ///88D
        ///89A
        ///90C
        ///91B
        ///92B
        ///93D
        ///94C
        ///95C
        ///96C
        ///9A7
        ///98C
        ///99A
        ///100C
        ///101B
        ///102D
        ///103A
        ///10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WordForm_Answers {
            get {
                return ResourceManager.GetString("WordForm_Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Have you got a new job? You must be very _____._A.excited_B.excite_C.exciting_D.none is correct
        ///2. “What _____ put salt in my coffee?” he exclaimed._A.stupid_B.foolish_C.fool_D.stupidity
        ///3. Many people are interested in watching _____._A.wilderness_B.wilds_C.wildlife_D.wildly
        ///4. Since the new chairman took over, the company has become increasingly _____._A.profit_B.profitable_C.profited_D.profiting
        ///5. I think she’s _____. Her books are brilliant._A.a genius_B.. a genie_C.a genus_D.genial
        ///6. America  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WordForm_Quizzes {
            get {
                return ResourceManager.GetString("WordForm_Quizzes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a_1|a|indefinite article|/ə/|uk_pron/a/a__/a__gb/a__gb_2.mp3|/ə/|us_pron/a/a__/a__us/a__us_2_rr.mp3
        ///a_2|A|noun|/eɪ/|uk_pron/a/a_1/a_1_g/a_1_gb_1_abbr.mp3|/eɪ/|us_pron/a/a__/a__us/a__us_1.mp3
        ///a_3|A|symbol|/eɪ/|uk_pron/a/a_1/a_1_g/a_1_gb_1_abbr.mp3|/eɪ/|us_pron/a/a__/a__us/a__us_1.mp3
        ///a_4|A|abbreviation|/eɪ/|uk_pron/a/a_1/a_1_g/a_1_gb_1_abbr.mp3|/eɪ/|us_pron/a/a__/a__us/a__us_1.mp3
        ///a_5|a-|prefix|/eɪ/|uk_pron/a/a__/a__1_/a__1_gb_1.mp3|/eɪ/|us_pron/a/a__/a__1_/a__1_us_1.mp3
        ///aa_1|AA|abbreviation|/ˌeɪ ˈeɪ/|u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string words {
            get {
                return ResourceManager.GetString("words", resourceCulture);
            }
        }
    }
}
