//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dictionary_Beta_1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dictionary_Beta_1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1024px_Speaker_Icon_svg {
            get {
                object obj = ResourceManager.GetObject("_1024px_Speaker_Icon_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap books {
            get {
                object obj = ResourceManager.GetObject("books", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a_1|https://www.oxfordlearnersdictionaries.com/media/english/uk_pron/a/a__/a__gb/a__gb_2.mp3
        ///a_2|https://www.oxfordlearnersdictionaries.com/media/english/uk_pron/a/a_1/a_1_g/a_1_gb_1_abbr.mp3
        ///a_3|https://www.oxfordlearnersdictionaries.com/media/english/uk_pron/a/a_1/a_1_g/a_1_gb_1_abbr.mp3
        ///a_4|https://www.oxfordlearnersdictionaries.com/media/english/uk_pron/a/a_1/a_1_g/a_1_gb_1_abbr.mp3
        ///a_5|https://www.oxfordlearnersdictionaries.com/media/english/uk_pron/a/a__/a__1_/a__1_gb_1.mp3
        ///aa_1|https://www.oxfor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string british {
            get {
                return ResourceManager.GetString("british", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1A
        ///2C
        ///3D
        ///4C
        ///5A
        ///6D
        ///7B
        ///8A
        ///9C
        ///10A
        ///11B
        ///12C
        ///13B
        ///14C
        ///15D
        ///16C
        ///17D
        ///18D
        ///19C
        ///20D
        ///21D
        ///22A
        ///23D
        ///24A
        ///25D
        ///26A
        ///27C
        ///28D
        ///29C
        ///30C
        ///31A
        ///32A
        ///33D
        ///34C
        ///35A
        ///36B
        ///37A
        ///38C
        ///39C
        ///40D
        ///41D
        ///42D
        ///43D
        ///44C
        ///45A
        ///46B
        ///47A
        ///48D
        ///49B
        ///50D
        ///51A
        ///52C
        ///53A
        ///54B
        ///55D
        ///56A
        ///57D
        ///58D
        ///59A
        ///60A
        ///61C
        ///62B
        ///63B
        ///64C
        ///65A
        ///66C
        ///67A
        ///68C
        ///69B
        ///70D
        ///71A
        ///72C
        ///73A
        ///74C
        ///75B
        ///76A
        ///77A
        ///78D
        ///79C
        ///80A
        ///81C
        ///82D
        ///83A
        ///84B
        ///85C
        ///86B
        ///87D
        ///88C
        ///89D
        ///90A
        ///91B
        ///92D
        ///93A
        ///94B
        ///95A
        ///96B
        ///97C
        ///98A
        ///99D
        ///100C
        ///101D
        ///102C
        ///103C
        ///10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Collocation_Answers {
            get {
                return ResourceManager.GetString("Collocation_Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. He was late so I decided to _____ time by window shopping._A. kill_B. miss_C. spend_D. waste 
        ///2. John felt a sharp _____ in his back._A. injury_B. wound_C. pain_D. ache 
        ///3. The tomatoes we ate at their house were home-_____._A. made_B. produced_C. done_D. grown 
        ///4. Turn up to page 24 to find out at a _____ which courses are available to you._A. look_B. stare_C. glance_D. glimpse 
        ///5. The boys have gone on a fishing _____ with their father._A. trip_B. journey_C. trek_D. hike 
        ///6. I like that photo very [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Collocation_Quizzes {
            get {
                return ResourceManager.GetString("Collocation_Quizzes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @a /ei, ə/
        ///*  danh từ,  số nhiều as,  a&apos;s
        ///- (thông tục) loại a, hạng nhất, hạng tốt nhất hạng rất tốt
        ///=his health is a+ sức khoẻ anh ta vào loại a
        ///- (âm nhạc) la
        ///=a sharp+ la thăng
        ///=a flat+ la giáng
        ///- người giả định thứ nhất; trường hợp giả định thứ nhất
        ///=from a to z+ từ đầu đến đuôi, tường tận
        ///=not to know a from b+ không biết tí gì cả; một chữ bẻ đôi cũng không biết
        ///*  mạo từ
        ///- một; một (như kiểu); một (nào đó)
        ///=a very cold day+ một ngày rất lạnh
        ///=a dozen+ một tá
        ///=a few+ một ít
        ///=all of a si [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSDL {
            get {
                return ResourceManager.GetString("CSDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1B
        ///2D
        ///3B
        ///4B
        ///5A
        ///6D
        ///7B
        ///8C
        ///9B
        ///10C
        ///11C
        ///12B
        ///13D
        ///14B
        ///15B
        ///16C
        ///17C
        ///18A
        ///19C
        ///20B
        ///21D
        ///22D
        ///23C
        ///24D
        ///25B
        ///26A
        ///27B
        ///28C
        ///29D
        ///30B
        ///31D
        ///32C
        ///33B
        ///34B
        ///35A
        ///36D
        ///37A
        ///38A
        ///39D
        ///40C
        ///41B
        ///42C
        ///43B
        ///44A
        ///45A
        ///46C
        ///47D
        ///48C
        ///49D
        ///50B
        ///51C
        ///52B
        ///53A
        ///54D
        ///55C
        ///56C
        ///57B
        ///58C
        ///59A
        ///60D
        ///61C
        ///62D
        ///63D
        ///64D
        ///65B
        ///66B
        ///67B
        ///68C
        ///69C
        ///70B
        ///71B
        ///72C
        ///73B
        ///74D
        ///75A
        ///76B
        ///77B
        ///78B
        ///79C
        ///80C
        ///81D
        ///82D
        ///83B
        ///84A
        ///85A
        ///86A
        ///87A
        ///88D
        ///89B
        ///90D
        ///91A
        ///92A
        ///93D
        ///94B
        ///95C
        ///96B
        ///97A
        ///98D
        ///99C
        ///100A
        ///101A
        ///102C
        ///103C
        ///10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Idiom_Answers {
            get {
                return ResourceManager.GetString("Idiom_Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. It finally _____ home to me that it was time to buy a place of my own._A. arrived_B. came_C. hit_D. reached 
        ///2. Well, it’s 7 p.m. I’d better hit the _____ if I want to get home before it’s dark_A. roof_B. headlines_C. newspaper_D. road 
        ///3. She’s the type who can’t sit on holiday and is always _____ the move._A. in_B. on_C. at_D. by 
        ///4. She had never been to Prague before, and she _____ in love with it straight away._A. dropped_B. fell_C. tripped_D. crashed 
        ///5. He didn’t speak a word of French when he [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Idiom_Quizzes {
            get {
                return ResourceManager.GetString("Idiom_Quizzes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abdomen_1|https://www.oxfordlearnersdictionaries.com/media/english/fullsize/i/ins/insec/insects.png
        ///abseil_1|https://www.oxfordlearnersdictionaries.com/media/english/fullsize/s/spo/sport/sports_extreme.png
        ///abseil_2|https://www.oxfordlearnersdictionaries.com/media/english/fullsize/s/spo/sport/sports_extreme.png
        ///abseiling_1|https://www.oxfordlearnersdictionaries.com/media/english/fullsize/s/spo/sport/sports_extreme.png
        ///accelerator_1|https://www.oxfordlearnersdictionaries.com/media/english/fullsize/c/car/c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string images {
            get {
                return ResourceManager.GetString("images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1D
        ///2C
        ///3B
        ///4A
        ///5A
        ///6C
        ///7D
        ///8D
        ///9B
        ///10B
        ///11B
        ///12C
        ///13C
        ///14C
        ///15B
        ///16B
        ///17A
        ///18B
        ///19B
        ///20A
        ///21A
        ///22B
        ///23D
        ///24C
        ///25B
        ///26A
        ///27A
        ///28A
        ///29D
        ///30C
        ///31B
        ///32A
        ///33D
        ///34B
        ///35A
        ///36D
        ///37A
        ///38A
        ///39B
        ///40D
        ///41C
        ///42D
        ///43B
        ///44C
        ///45C
        ///46D
        ///47B
        ///48C
        ///49D
        ///50C
        ///51D
        ///52A
        ///53B
        ///54C
        ///55D
        ///56C
        ///57B
        ///58B
        ///59D
        ///60C
        ///61D
        ///62C
        ///63C
        ///64D
        ///65C
        ///66A
        ///67B
        ///68B
        ///69A
        ///70C
        ///71D
        ///72D
        ///73A
        ///74D
        ///75C
        ///76A
        ///77B
        ///78C
        ///79B
        ///80B
        ///81B
        ///82C
        ///83B
        ///84B
        ///85A
        ///86B
        ///87C
        ///88B
        ///89B
        ///90C
        ///91C
        ///92A
        ///93D
        ///94D
        ///95C
        ///96A
        ///97C
        ///98C
        ///99B
        ///100A
        ///101A
        ///102A
        ///103D
        ///10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Phrasal_Verbs_Answers {
            get {
                return ResourceManager.GetString("Phrasal_Verbs_Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. We are _____ down too many trees all over the world._A. breaking_B. knocking_C. pushing_D. cutting 
        ///2. She has not yet got _____ her recent illness._A. by_B. through_C. over_D. out of 
        ///3. Everyone is going to take _____ in the game._A. place_B. part_C. participation_D. role 
        ///4. John was tidying the living room while I was cleaning _____ the dirt from thr dishes._A. away_B. out_C. up_D. off 
        ///5. “It takes about 2 hours, so we should _____ at about six o’clock.”_A. get in_B. get in it_C. get it in_D. ge [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Phrasal_Verbs_Quizzes {
            get {
                return ResourceManager.GetString("Phrasal_Verbs_Quizzes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quiz {
            get {
                object obj = ResourceManager.GetObject("quiz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
